[IT-1531] Add a check for stack_tags
Sage-Bionetworks-IT/pre-commit-provisioner pull request #11
Opened 2022-02-17 18:05 UTC by zaro0508

Add a pre-commit hook to make sure users define `stack_tags` in
sceptre configs files.  The idea is to use this in the scicomp provisioner
to require users to define tags when provisioning AWS resources.

2022-02-17 18:23 UTC, DiepThach reviewed
I can follow the instructions but I don't fully understand all the steps.

2022-02-17 19:27 UTC, brucehoff requested changes

2022-02-17 19:27 UTC, brucehoff commented on linters/check_stack_tags.py
> +        if 'stack_tags' not in config:
I don't understand how this ensures that the CostCenter tag is added with a valid cost center value).

2022-02-17 21:29 UTC, brucehoff commented on linters/check_stack_tags.py
> +        if 'stack_tags' not in config:
Yes, I don't see how that satisfies, IT-1531.  We need a mechanism to direct users to add a `cost center` tag to their provisioned resources and to use values which are based on the program codes that come from Finance.

2022-02-18 00:27 UTC, zaro0508 commented on linters/check_stack_tags.py
> +        if 'stack_tags' not in config:
ahh yes, you guys are correct. i need to figure out how to allow users to configure this hook to check that specific tags are actually defined.

2022-03-08 19:57 UTC, zaro0508 commented
replacing this PR by using sceptrelint in PR https://github.com/Sage-Bionetworks/sandbox-provisioner/pull/404 and PR https://github.com/Sage-Bionetworks/scicomp-provisioner/pull/514

2022-03-08 19:57 UTC, closed without merging